---
title: "gps"
author: "Stats"
date: '2018 7 13 '
output: html_document
---

```{r}
gps1 <- read.csv('gps_u00.csv',header = T)
gps <- gps1[,0:5]
colnames(gps) = c('provider','network_type','accuracy','latitude','longitude')
gps

gps2 <- read.csv('gps_u41.csv')
colnames(gps2) = c('provider','network_type','accuracy','latitude','longitude')
gps2 <- gps2[,0:5]
gps2
```

```{r}
str(gps)
```
```{r}
library(fpc)
n <- 4316
x <- cbind(runif(10, 0, 10)+rnorm(n, sd=0.2), runif(10, 0, 10)+rnorm(n,sd=0.2))
a <- dbscan(gps[,4:5],eps = 0.45,MinPts = 10)
gps[4:5]
head(a)
plot(x[a$cluster %in% 1:5,])
a$cluster
center <- sapply(a$cluster, mean)
center
```

```{r}
install.packages('ggmap')
library(ggmap)
map.usa <- get_map('New Hampshire', zoom = 12)
ggmap(map.usa) 
head(gps)

library(dplyr)
get_map("New Hampshire", zoom = 12) %>% ggmap()

map.usa + geom_point(data=gps, aes(x=longitude, y=latitude, size=Freq),
colour = 'gray', alpha=0.3)
gps1 <- gps[3:5]
str(gps1)
as.numeric(gps2)


getmap <- get_googlemap("New Hampshire")
ggmap(getmap)

gps
cent <- sapply(gps[4:5], mean)
map <- ggmap(get_googlemap(center = cent, zoom=5, maptype='roadmap', color='bw',scale = '2'), extent='device')
map

map <- get_map(location= 'New Hampshire', zoom=7, maptype='roadmap', color='bw')
map

ggmap(map) + geom_point(data=gps[4:5], aes(x=longitude, y=latitude, color='red')) + geom_point(data=gps2[4:5], aes(x=longitude, y=latitude, color='green'))

```

